# Generated by Django 6.0.5 on 2026-05-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_solicitud', models.CharField(choices=[('consulta', 'Consulta'), ('tramite', 'Cita para trámite')], max_length=20)),
                ('fecha', models.DateField()),
                ('horario', models.CharField(choices=[('09:00', '9:00 hs'), ('10:00', '10:00 hs'), ('11:00', '11:00 hs')], max_length=10)),
                ('comentarios', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha', 'horario'],
                'unique_together': {('fecha', 'horario')},
            },
        ),
    ]
