# Generated by Django 6.0.5 on 2026-05-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='horario',
            field=models.CharField(choices=[('09:00', '9:00 hs'), ('10:00', '10:00 hs'), ('11:00', '11:00 hs'), ('12:00', '12:00 hs')], max_length=10),
        ),
    ]
