# Generated by Django 6.0.5 on 2026-05-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_resena'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaNoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
