# Generated by Django 6.0.5 on 2026-05-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_dianodisponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario', models.CharField(blank=True, choices=[('', 'Día completo'), ('09:00', '9:00 hs'), ('10:00', '10:00 hs'), ('11:00', '11:00 hs'), ('12:00', '12:00 hs')], max_length=10)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha', 'horario'],
                'unique_together': {('fecha', 'horario')},
            },
        ),
        migrations.DeleteModel(
            name='DiaNoDisponible',
        ),
    ]
