# Generated by Django 6.0.5 on 2026-05-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_bloqueoagenda_delete_dianodisponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
